#
# This file contains configuration flags to customize your site
#

# Site details (displayed in the header)
author: Company
name: Company Blog
title: Company Blog
description: A Description of the Blog
keywords: "money, optimism, achievement"
logo: images/logo.jpg

# Company details
company:
  cta:
    text: "Visit our website"
    url: "/"
  socials:
    github: "username"
    x: "username"
    facebook: "username"
    youtube: "username"
    discord: "username"
    pinterest: "username"
    telegram: "username"
    email: "username"
    phone: "username"
    instagram: "username"
    tiktok: "username"
    linkedin: "username"
  icon_size: "24"
  colors:
    background: "#19191f"
    foreground: "#f1f1f1"
    accent: "#E74727"
  fonts:
    google:
      - "Roboto:ital,wght@0,100..900;1,100..900"
    heading: "'Helvetica Neue', 'Roboto'"
    body: "'Helvetica Neue', 'Roboto'"

# Navigation items
navigation:
  header:
    - title: "CTA"
      url: "/"
    - title: "CTA"
      url: "/"
    - title: "CTA"
      url: "/"
  footer:
    - title: "Terms and Conditions"
      url: "/terms-and-conditions"
    - title: "Privacy Policy"
      url: "/privacy-policy"
    - title: "Cookie Policy"
      url: "/cookie-policy"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://127.0.0.1:4000/

# Paginate after X amount of posts
paginate: 3

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

#
# NOTHING TO CHANGE BEYOND THIS POINT
#

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# ONLY NECESSARY ON SUB-PAGE / GITHUB-BASED HOSTING
baseurl: 

# Theme used as a base
theme: jekyll-swiss

# Slug of paginated page
paginate_path: "/page-:num/"

# Permalink slug (DO NOT TOUCH)
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap
  - jekyll-feed # Create an Atom RSS feed
  - jekyll-paginate # Support pagination of posts

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - __init/
  - init_mac.command
  - init_windows.bat